# Generated by Django 3.0.5 on 2020-05-10 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shouquanma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_code', models.CharField(default='', max_length=16, verbose_name='授权码')),
                ('is_active', models.CharField(default=0, max_length=10, verbose_name='激活时间')),
                ('expire', models.IntegerField(default=0, verbose_name='过期时间')),
                ('online', models.BooleanField(default=0, verbose_name='是否在线')),
                ('device_id', models.CharField(default='', max_length=100, verbose_name='设备id')),
                ('heart_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='心跳时间')),
                ('active_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='激活时间')),
                ('expire_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='到期时间')),
                ('initial_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='初始化时间')),
            ],
            options={
                'db_table': 'code',
            },
        ),
    ]
